version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    command: sh -c "./bin/shakapacker-dev-server && rm -f tmp/pids/server.pid && yarn install --check-files && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://myapp:password@db:3306/myapp_development
    stdin_open: true
    tty: true

volumes:
  db_data:
