# # ADMIN
@email = "admin@admin.com"
@password = "admin-password"


# EMPLOYEE
@employee_name = "Shanon Lucas"
@employee_email = "shanon@lucas.test"
@employee_password = "72c1cshanon"

### 
# @name login
POST http://localhost:3000/login 
content-type: application/json

{
  "email": {{email}},
  "password": {{password}}
}


###
# @name createEmployee
POST http://localhost:3000/employee
content-type: application/json
Authorization: Bearer {{ login.response.body.$.token }}

{
  "user": {
    "name": {{employee_name}},
    "email": {{employee_email}}
  }
}

###
# @name updateEmployee
PUT http://localhost:3000/employee/{{ createEmployee.response.body.$.employee.id }}
content-type: application/json
Authorization: Bearer {{ login.response.body.$.token }}

{
  "user": {
    "id": "{{ createEmployee.response.body.$.employee.id }}",
    "name": {{employee_name}},
    "email": {{employee_email}}
  }
}
