# # ADMIN
@email = "tiera@greenfelde.test"
@password = "admin-password"


# EMPLOYEE
@employee_name = "Shanon Murrey"
@employee_email = "shanon@2024-09-10T14:33:20.58.test"
@employee_password = "72c1cshanon"

### 
# @name login
POST http://localhost:3000/login 
content-type: application/json

{
  "email": {{email}},
  "password": {{password}}
}


###
# @name createEmployee
POST http://localhost:3000/employee
content-type: application/json
Authorization: Bearer {{ login.response.body.$.token }}

{
  "user": {
    "name": {{employee_name}},
    "email": {{employee_email}}
  }
}
